name: hasura_live
description: Query, Mutation and Subscription with Hasura over websocket. 
version: 0.1.0
homepage: https://github.com/osaxma/hasura_live

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web_socket_channel: ^2.0.0
  logging: ^1.0.2


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
